/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_david_study_JNITest */

#ifndef _Included_com_david_study_JNITest
#define _Included_com_david_study_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_david_study_JNITest
 * Method:    printJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_david_study_JNITest_printJNI
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
